# NumPy Arrays

Numpy is the Fundamental Python package for scientific computing, it adds the capabilties of N dimension Arrays, elementby element operations core mathematical operation like linear algebra and the abiltiy to wrap code.
We will cover most of these aspects in this chapter by first covering what Numpy arrays are and their advantages versus Python lists and dictionaries.


Python stores data in several different ways, but the most popular methods are lists and dictionaries. The Python list object can store nearly any type of Python object as an element. But operating on the elements in a list can only be done through iterative loops, which is computationally inefficient in Python. The NumPy package enables users to overcome the shortcomings of the Python lists by providing a data storage object called ndarray.

The ndarray is similar to lists, but rather than being highly flexible by storing different types of objects in one list, only the same type of element can be stored in each column.For example, with a Python list, you could make the first element a list and the second another list or dictionary. With NumPy arrays, you can only store the same type of element, e.g., all elements must be floats, integers, or strings. Despite this limitation,ndarray wins hands down when it comes to operation times, as the operations are sped up significantly. Using the %timeit magic command in IPython, we compare the power of NumPy ndarray versus Python lists in terms of speed.

In [2]:
import numpy as np


In [3]:
arr = np.arange(1e7)
larr = arr.tolist()

In [4]:
import numpy as np
import time
import sys

# let's declare the size
Size = 100000

# Creating two lists
list1 = range(Size)
list2 = range(Size)

# Creating two NumPy arrays
arr1 = np.arange(Size)
arr2 = np.arange(Size)

# Calculating time for Python list
start = time.time()
result = [x+y for x, y in zip(list1, list2)]
          
print("Time for Python List in msec: ", (time.time() - start) * 1000)

# Calculating time for NumPy array 
arr = np.concatenate((arr1, arr2))
start = time.time()
result = [z for z in arr]
print("Time for NumPy array in msec: ", (time.time()- start) * 1000)


Time for Python List in msec:  24.003982543945312
Time for NumPy array in msec:  40.0083065032959


In [5]:
x = np.random.randn(10)

In [6]:
x

array([ 0.80191775,  0.01934015,  0.40905105,  1.10721523,  0.93254586,
       -0.48693658, -0.20287461, -0.08664068,  1.08282684,  0.25123494])

In [7]:
y =np.random.randint(5, 50, 10)

In [8]:
y

array([40, 12, 48, 10, 27, 16,  6, 36,  8, 26])

In [9]:
s =np.eye(5)

In [10]:
s

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
z =np.ones(5)

In [12]:
z

array([1., 1., 1., 1., 1.])

In [13]:
exarr = np.zeros((3,3,3))
exarr


array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [14]:
# Converting list to np array
alist = [4,5,6,7,8]
exarr2 = np.array(alist)

In [15]:
type(exarr2)
# shows type of data type

numpy.ndarray

In [16]:
# what is we want to create an array going from 0 to 100 ?
arr4 = np.arange(100)
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [21]:
# Or 10 to 100 ?
arr5 = np.arange(10, 100)
arr5
#if you want 100 steps from 0 to 1
arr6 = arr5.reshape((9,10))
arr6


array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [22]:
print(arr6.shape)

(9, 10)


In [23]:
arr7 = np.zeros(2, dtype=int)

In [24]:
arr8 =np.zeros(2, dtype=np.float32)

In [25]:
arr7 
arr8

array([0., 0.], dtype=float32)

In [27]:
#arr8 =np.loadtxt("example.txt,)

In [ ]:
# importing matrix
A = np.matrix([[3,6,-5],
             [1, -3, 2],
             [5, -1, 4]])
B = no,